#!/bin/bash
echo "Checking azerothcore ..."
cd ~/azerothcore-wotlk
git pull origin master
echo 
echo "Checking playerbots ..."
cd ~/azerothcore-wotlk/modules/mod-playerbots
git pull origin master
echo
echo "Checking transmog ..."
cd ~/azerothcore-wotlk/modules/mod-transmog
git pull origin master
echo
echo "Checking eluna ..."
cd ~/azerothcore-wotlk/modules/mod-eluna
git pull origin master
echo
echo "Checking dugeonrespawn ..."
cd ~/azerothcore-wotlk/modules/DungeonRespawn
git pull origin master
echo
echo "Checking ah-bot ..."
cd ~/azerothcore-wotlk/modules/mod-ah-bot
git pull origin master
echo
while true; do
    read -p "Update servers? " yn
    case $yn in
        [Yy]* ) make install; break;;
        [Nn]* ) exit;;
        * ) echo "Please answer yes or no.";;
    esac
done
make ../ -DCMAKE_INSTALL_PREFIX=/azerothcore-fordragon/azeroth-server/ -DCMAKE_C_COMPILER=/usr/bin/clang -DCMAKE_CXX_COMPILER=/usr/bin/clang++ -DWITH_WARNINGS=1 -DTOOLS_BUILD=all -DSCRIPTS=static -DMODULES=static
